/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminPointsRouteImport } from './routes/admin.points'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as ApiAuthKickStartRouteImport } from './routes/api/auth/kick.start'
import { Route as ApiAuthKickCallbackRouteImport } from './routes/api/auth/kick.callback'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPointsRoute = AdminPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthKickStartRoute = ApiAuthKickStartRouteImport.update({
  id: '/api/auth/kick/start',
  path: '/api/auth/kick/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthKickCallbackRoute = ApiAuthKickCallbackRouteImport.update({
  id: '/api/auth/kick/callback',
  path: '/api/auth/kick/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/points': typeof AdminPointsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/kick/callback': typeof ApiAuthKickCallbackRoute
  '/api/auth/kick/start': typeof ApiAuthKickStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/points': typeof AdminPointsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/kick/callback': typeof ApiAuthKickCallbackRoute
  '/api/auth/kick/start': typeof ApiAuthKickStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/points': typeof AdminPointsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/kick/callback': typeof ApiAuthKickCallbackRoute
  '/api/auth/kick/start': typeof ApiAuthKickStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/shop'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/permissions'
    | '/admin/points'
    | '/admin/shop'
    | '/admin/'
    | '/api/auth/kick/callback'
    | '/api/auth/kick/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/shop'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/permissions'
    | '/admin/points'
    | '/admin/shop'
    | '/admin'
    | '/api/auth/kick/callback'
    | '/api/auth/kick/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/shop'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/permissions'
    | '/admin/points'
    | '/admin/shop'
    | '/admin/'
    | '/api/auth/kick/callback'
    | '/api/auth/kick/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  ApiAuthKickCallbackRoute: typeof ApiAuthKickCallbackRoute
  ApiAuthKickStartRoute: typeof ApiAuthKickStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/points': {
      id: '/admin/points'
      path: '/points'
      fullPath: '/admin/points'
      preLoaderRoute: typeof AdminPointsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/kick/start': {
      id: '/api/auth/kick/start'
      path: '/api/auth/kick/start'
      fullPath: '/api/auth/kick/start'
      preLoaderRoute: typeof ApiAuthKickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/kick/callback': {
      id: '/api/auth/kick/callback'
      path: '/api/auth/kick/callback'
      fullPath: '/api/auth/kick/callback'
      preLoaderRoute: typeof ApiAuthKickCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPointsRoute: typeof AdminPointsRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLogsRoute: AdminLogsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPointsRoute: AdminPointsRoute,
  AdminShopRoute: AdminShopRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  ApiAuthKickCallbackRoute: ApiAuthKickCallbackRoute,
  ApiAuthKickStartRoute: ApiAuthKickStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
